{
 "title": "Maakportal status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 16, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp - interval '3 hour' AS \"time\",\n  host AS metric,\n  loading_time AS \"loading_time\"\nFROM monitoring_entry\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "alertlist",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Log",
   "type": "table",
   "gridPos": { "h": 16, "w": 5, "x": 19, "y": 11 },
   "targets": [
    {
     "rawSql": "select timestamp,host,response from monitoring_entry;"
    }
   ]
  },
  {
   "title": "Host status",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT host, response, keyword_found::boolean\nFROM monitoring_entry\nWHERE id IN (\n    SELECT MAX(id)\n    FROM monitoring_entry\n    GROUP BY host\n);"
    }
   ]
  },
  {
   "title": "Response other than 200",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  host AS metric,\n  response\nFROM monitoring_entry\nwhere response != 200\nORDER BY 1,2"
    }
   ]
  }
 ]
}